name: Unity Build Pipeline

on: [push, pull_request]

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Activate Unity License
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: echo "$UNITY_LICENSE" | base64 --decode > UnityLicense.ulf

      - name: Build Unity Game
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2021.3.10f1 
          targetPlatform: StandaloneWindows64

