name: Unity Build and Test Pipeline

on: [push, pull_request]  
jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  

      - name: Install Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2021.3.10f1 
          targetPlatform: StandaloneWindows64 

      - name: Build Game
        run: |
          echo "Building the game..."
          unity-editor -quit -batchmode -buildWindowsPlayer "Builds/MyGame.exe"

  test:
    name: Run Unity Tests
    runs-on: ubuntu-latest
    needs: build  # Runs only if build succeeds

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Unity Tests
        run: |
          echo "Running Unity tests..."
          unity-editor -runTests -batchmode -testResults "TestResults.xml"
