name: Unity Build and Test Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and Test Unity Project
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Activate Unity License
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: echo "$UNITY_LICENSE" | base64 --decode > UnityLicense.ulf

      - name: Build Unity Game
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2021.3.10f1
          targetPlatform: StandaloneWindows64

      - name: Run Unity Tests
        run: |
          echo "Running tests..."
          unity-editor -batchmode -runTests -testResults TestResults.xml

      - name: Generate Documentation
        run: |
          echo "Generating documentation..."
          doxygen Doxyfile
